import { InterviewStream } from '../types';

export const INTERVIEW_STREAMS: InterviewStream[] = [
    {
        id: 'software-developer',
        name: 'Software Developer',
        icon: '💻',
        description: 'Full software engineering interview with DSA, system design, and coding challenges',
        difficulty: 'Hard',
        duration: '~2 hours',
        color: 'from-blue-500 to-cyan-500',
    },
    {
        id: 'frontend-developer',
        name: 'Frontend Developer',
        icon: '🎨',
        description: 'React, CSS, accessibility, performance optimization, and UI coding challenges',
        difficulty: 'Medium',
        duration: '~2 hours',
        color: 'from-purple-500 to-pink-500',
    },
    {
        id: 'backend-developer',
        name: 'Backend Developer',
        icon: '⚙️',
        description: 'APIs, databases, system design, microservices, and server-side coding',
        difficulty: 'Hard',
        duration: '~2 hours',
        color: 'from-green-500 to-emerald-500',
    },
    {
        id: 'fullstack-developer',
        name: 'Full Stack Developer',
        icon: '🔄',
        description: 'End-to-end web development covering frontend, backend, and deployment',
        difficulty: 'Hard',
        duration: '~2 hours',
        color: 'from-indigo-500 to-blue-500',
    },
    {
        id: 'data-scientist',
        name: 'Data Scientist',
        icon: '📊',
        description: 'ML algorithms, statistics, data analysis, Python, and case studies',
        difficulty: 'Hard',
        duration: '~2 hours',
        color: 'from-orange-500 to-amber-500',
    },
    {
        id: 'devops-engineer',
        name: 'DevOps Engineer',
        icon: '🚀',
        description: 'CI/CD, Docker, Kubernetes, cloud platforms, and infrastructure scenarios',
        difficulty: 'Medium',
        duration: '~2 hours',
        color: 'from-teal-500 to-cyan-500',
    },
    {
        id: 'hr-manager',
        name: 'HR Manager',
        icon: '👥',
        description: 'Employee relations, conflict resolution, policies, and behavioral scenarios',
        difficulty: 'Medium',
        duration: '~1.5 hours',
        color: 'from-rose-500 to-pink-500',
    },
    {
        id: 'chartered-accountant',
        name: 'Chartered Accountant',
        icon: '📈',
        description: 'Financial accounting, taxation, auditing, and financial case studies',
        difficulty: 'Hard',
        duration: '~2 hours',
        color: 'from-yellow-500 to-orange-500',
    },
    {
        id: 'business-analyst',
        name: 'Business Analyst',
        icon: '📋',
        description: 'Requirements gathering, process modeling, stakeholder management, and case analysis',
        difficulty: 'Medium',
        duration: '~1.5 hours',
        color: 'from-sky-500 to-blue-500',
    },
    {
        id: 'cybersecurity-analyst',
        name: 'Cybersecurity Analyst',
        icon: '🔒',
        description: 'Network security, vulnerability assessment, incident response, and compliance',
        difficulty: 'Hard',
        duration: '~2 hours',
        color: 'from-red-500 to-rose-500',
    },
    {
        id: 'product-manager',
        name: 'Product Manager',
        icon: '🎯',
        description: 'Product strategy, prioritization, user research, and metrics analysis',
        difficulty: 'Medium',
        duration: '~1.5 hours',
        color: 'from-violet-500 to-purple-500',
    },
    {
        id: 'uiux-designer',
        name: 'UI/UX Designer',
        icon: '✨',
        description: 'Design thinking, user research, prototyping, and usability evaluation',
        difficulty: 'Medium',
        duration: '~1.5 hours',
        color: 'from-fuchsia-500 to-pink-500',
    },
];
